=== dangari/Herobattle/Herobattle/Source/Herobattle/Definitions/skill.dtd
<!ELEMENT skills (profession)*>

<!ELEMENT profession (spell)*>
<!ATTLIST  profession
	value CDATA #REQUIRED
>

<!ELEMENT spell (name, costs, casttime, cooldown, targettype, range, weapon?, effects)>
<!ATTLIST spell
  type CDATA #REQUIRED
  >
<!-- spell nodes  -->
<!ELEMENT name EMPTY>
<!ATTLIST name
  value CDATA #REQUIRED
  >
<!ELEMENT costs EMPTY>
<!ATTLIST costs
  value CDATA #REQUIRED
  >
<!ELEMENT casttime EMPTY>
<!ATTLIST casttime
  value CDATA #REQUIRED
  >
<!ELEMENT cooldown EMPTY>
<!ATTLIST cooldown
  value CDATA #REQUIRED
  >
<!ELEMENT targettype EMPTY>
<!ATTLIST targettype
  value (SELF|SELFFREND|FRIEND|ENEMY) #REQUIRED
  >
<!ELEMENT range EMPTY>
<!ATTLIST range
  value CDATA #REQUIRED
  >

<!ELEMENT weapon EMPTY>
<!ATTLIST weapon 
  value CDATA #REQUIRED
  >


<!ELEMENT effects (impact)>
<!-- impact nodes  -->
<!ELEMENT impact (heal|damage|buff|condition|foreach|when|remove)*>
<!ELEMENT heal (step?)*>
<!ATTLIST heal 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  trigger (HEAL|DAMAGE) #IMPLIED
  >
<!ELEMENT damage (step?)*>
<!ATTLIST damage 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  trigger (HEAL|DAMAGE) #IMPLIED
  >
<!ELEMENT buff (step?|heal|damage|buff|regeneration|foreach|when|block|knockdown|skillcooldown)*>
<!ATTLIST buff 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  usage CDATA #REQUIRED
  >
<!ELEMENT condition (step)*>
<!ATTLIST condition 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  >
<!ELEMENT regeneration (step?)*>
<!ATTLIST regeneration 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  >
<!ELEMENT foreach (heal|damage|buff|condition|regeneration|when)*>
<!ATTLIST foreach
  type CDATA #REQUIRED
  >
<!ELEMENT when (whencondition, then)>
<!ATTLIST when
  value CDATA #REQUIRED
  >
<!ELEMENT whencondition (attack|hp)>

<!ELEMENT remove (step?)*>
<!ATTLIST remove 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!ELEMENT knockdown (step?)>
<!ATTLIST knockdown 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >
<!ELEMENT skillcooldown (step?)>
<!ATTLIST skillcooldown 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!-- sub nodes -->
<!ELEMENT then (heal|damage|buff|condition|regeneration|knockdown|skillcooldown)*>

<!ELEMENT attack EMPTY>
<!ATTLIST attack
  type CDATA #REQUIRED
  >
<!ELEMENT hp EMPTY>
<!ATTLIST hp
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  >

<!ELEMENT step EMPTY>
<!ATTLIST step
  key CDATA #REQUIRED
  value CDATA #REQUIRED
  >

<!ELEMENT block (step?)*>
<!ATTLIST block
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  usage CDATA #REQUIRED
  >

=== dangari/Herobattle/Herobattle/Source/Herobattle/Definitions/skill.xml
<!DOCTYPE skills SYSTEM "skill.dtd">
<skills>
	<profession value="ELEMENTALIST">
		<spell type="SPELL">
			<name value="Immolate"/>
			<costs value="10"/>
			<casttime value="1"/>
			<cooldown value="5"/>
			<targettype value="ENEMY"/>
			<effects>
				<impact>
					<damage value="20" scaling="FIRE_MAGIC" type="FIRE">
						<step key="1" value="24"/>
						<step key="2" value="27"/>
					</damage>
          <condition type="BURNING"  value="1" scaling="FIRE_MAGIC">
            <step key="4" value="2"/>
            <step key="12" value="3"/>
          </condition>
				</impact>
			</effects>
		</spell>
	</profession>

	<profession value="MONK">
		<spell type="SPELL">
			<name value="Word of Healing"/>
			<costs value="5"/>
			<casttime value="0.75"/>
			<cooldown value="3"/>
			<targettype value="SELF_ALLY"/>
			<effects>
				<impact>
					<heal value="5" scaling="HEALING_PRAYERS">
						<step key="1" value="11"/>
						<step key="2" value="18"/>
						<step key="3" value="24"/>
					</heal>
					<when value="TARGERT">
						<whencondition>
							<hp value="50" type="-"/>
						</whencondition>
						<then>
							<heal value="30" scaling="HEALING_PRAYERS">
								<step key="1" value="36"/>
								<step key="2" value="41"/>
								<step key="3" value="47"/>
							</heal>
						</then>
					</when>
				</impact>
			</effects>
		</spell>

		<spell type="SPELL">
			<name value="Guardian"/>
			<costs value="5"/>
			<casttime value="1"/>
			<cooldown value="4"/>
			<targettype value="SELF_ALLY"/>
			<effects>
				<impact>
					<buff value="2" type="ENCHANTMENT" scaling="PROTECTION_PRAYERS">
						<step key="2" value="3"/>
						<step key="5" value="4"/>
						<step key="11" value="6"/>
            <block type="ATTACKS" value="50" scaling= "NONE" usage="INF"/>
					</buff>
				</impact>
			</effects>
		</spell>

		<spell type="SPELL">
			<name value="Mend Ailment"/>
			<costs value="5"/>
			<casttime value="0.75"/>
			<cooldown value="5"/>
			<targettype value="SELF_ALLY"/>
			<effects>
				<impact>
					<remove value="1" type="CONDITION" scaling="NONE"/>
					<foreach type="CONDITION">
						<heal value="30" scaling="PROTECTION_PRAYERS">
							<step key="1" value="5"/>
							<step key="2" value="9"/>
							<step key="3" value="14"/>
						</heal>
					</foreach>
				</impact>
			</effects>
		</spell>

	</profession>

	<profession value="WARRIOR">
		<spell type="UNIQUE_BUFF">
			<name value="Shield Bash"/>
			<costs value="5"/>
			<casttime value="0"/>
			<cooldown value="20"/>
			<targettype value="SELF"/>
			<weapon value="SHIELD"/>
      <effects>
        <impact>
			    <buff value="5" type="STANCE" scaling="STRENGHT">
				    <block type="ATTACKSKILLS" value="100" scaling="NONE" usage="1"/>
				    <step key="2" value="6"/>
				    <step key="4" value="7"/>
				    <step key="7" value="8"/>
				    <when value="TARGET">
					    <whencondition>
						    <attack type="MELEEATACKSKILL"/>
					    </whencondition>
					    <then>
                <knockdown value="2" scaling="NONE"/>
                <skillcooldown value="15" scaling="NONE"/>
					    </then>	
				    </when>
			    </buff>
        </impact>
      </effects>
		</spell>
	</profession>

	<profession value="DERWISH">
		<spell type="SPELL">
			<name value="Mystic Regeneration"/>
			<costs value="10"/>
			<casttime value="0.25"/>
			<cooldown value="12"/>
			<targettype value="SELF"/>
      <effects>
        <impact>
			    <buff value="5" type="ENCHANTMENT" scaling="EARTH_PRAYERS">
				    <step key="1" value="6"/>
				    <step key="2" value="7"/>
				    <step key="3" value="8"/>
				    <foreach type="ENCHANTMENT">
              <regeneration value="1" scaling="EARTH_PRAYERS" type="HEALTH">
						    <step key="3" value="2"/>
						    <step key="8" value="3"/>
					    </regeneration>
				    </foreach>
			    </buff>
        </impact>
      </effects>
		</spell>
	</profession>
</skills>

=== dangari/Herobattle/Herobattle/Source/Herobattle/Definitions/Warrior.xml
<!DOCTYPE skills SYSTEM "skill.dtd">
<skills>
  <profession value="PARAGON">
    <spell type="RANGEATTACK">
      <name value="Barbed Spear"/>
      <costs value="2" type="ADRENALINE"/>
      <casttime value="0"/>
      <cooldown value="0"/>
      <targettype value="ENEMY"/>
      <range value="800"/>
      <weapon value="SPEAR"/>
      <effects>
        <impact>
          <condition value="5" scaling="SPEAR_MASTERY" target="TARGET" type="BLEEDING">
            <step key="1" value="6"/>
            <step key="2" value="7"/>
            <step key="3" value="8"/>
            <step key="4" value="9"/>
            <step key="5" value="10"/>
            <step key="6" value="11"/>
            <step key="7" value="12"/>
            <step key="8" value="13"/>
            <step key="9" value="14"/>
            <step key="10" value="15"/>
            <step key="11" value="16"/>
            <step key="12" value="17"/>
            <step key="13" value="18"/>
            <step key="14" value="19"/>
          </condition>
        </impact>
      </effects>
    </spell>

    <spell type="RANGEATTACK">
      <name value="Maiming Spear"/>
      <costs value="5" type="MANA"/>
      <casttime value="0"/>
      <cooldown value="5"/>
      <targettype value="ENEMY"/>
      <range value="800"/>
      <weapon value="SPEAR"/>
      <effects>
        <impact>
          <when value="TARGET">
            <whencondition>
              <condi type="BLEEDING"/>
            </whencondition>
            <then>
              <condition value="5" scaling="SPEAR_MASTERY" target="TARGET" type="CRIPPLED">
                <step key="1" value="6"/>
                <step key="2" value="7"/>
                <step key="3" value="8"/>
                <step key="4" value="9"/>
                <step key="5" value="10"/>
                <step key="6" value="11"/>
                <step key="7" value="12"/>
                <step key="8" value="13"/>
                <step key="9" value="14"/>
                <step key="10" value="15"/>
                <step key="11" value="16"/>
                <step key="12" value="17"/>
                <step key="13" value="18"/>
                <step key="14" value="19"/>
              </condition>
            </then>
          </when>
        </impact>
      </effects>
    </spell>

    <spell type="RANGEATTACK">
      <name value="Blazing Spear"/>
      <costs value="6" type="ADRENALINE"/>
      <casttime value="0"/>
      <cooldown value="0"/>
      <targettype value="ENEMY"/>
      <range value="800"/>
      <weapon value="SPEAR"/>
      <effects>
        <impact>
          <damage value="5" scaling="SPEAR_MASTERY" target="TARGET" type="ATTACK">
            <step key="1" value="6"/>
            <step key="2" value="8"/>
            <step key="3" value="9"/>
            <step key="4" value="10"/>
            <step key="5" value="12"/>
            <step key="6" value="13"/>
            <step key="7" value="14"/>
            <step key="8" value="16"/>
            <step key="9" value="17"/>
            <step key="10" value="18"/>
            <step key="11" value="20"/>
            <step key="12" value="21"/>
            <step key="13" value="22"/>
            <step key="14" value="24"/>
          </damage>
          <condition value="1" scaling="SPEAR_MASTERY" target="TARGET" type="BURNING">
            <step key="4" value="2"/>
            <step key="12" value="3"/>
          </condition>
        </impact>
      </effects>
    </spell>
  </profession>
</skills>

=== dangari/Herobattle/Herobattle/Source/Herobattle/Definitions/EleHero.xml
<!DOCTYPE skills SYSTEM "skill.dtd">
<skills>
  <profession value="ELEMENTARMAGE">
    <spell type="SPELL">
      <name value="Mind Blast"/>
      <costs value="5" type="MANA"/>
      <casttime value="1"/>
      <cooldown value="2"/>
      <targettype value="ENEMY"/>
      <range value="800"/>
      <effects>
        <impact>
          <damage value="15" scaling="FIRE_MAGIC"  type="FIRE" target="TARGET">
            <step key="1" value="18"/>
            <step key="2" value="21"/>
            <step key="3" value="24"/>
            <step key="4" value="27"/>
            <step key="5" value="30"/>
            <step key="6" value="33"/>
            <step key="7" value="36"/>
            <step key="8" value="39"/>
            <step key="9" value="42"/>
            <step key="10" value="45"/>
            <step key="11" value="48"/>
            <step key="12" value="51"/>
            <step key="13" value="54"/>
            <step key="14" value="58"/>
          </damage>
          <when value="TARGET">
            <whencondition>
              <mana value="50" type="-"/>
            </whencondition>
            <then>
              <givemana value="1" scaling="FIRE_MAGIC" target="SELF">
                <step key="2" value="2"/>
                <step key="4" value="3"/>
                <step key="6" value="4"/>
                <step key="8" value="5"/>
                <step key="10" value="6"/>
                <step key="12" value="7"/>
                <step key="14" value="8"/>
              </givemana>
            </then>
          </when>
        </impact>
      </effects>
    </spell>
    
    <spell type="SPELL">
      <name value="Immolate"/>
      <costs value="10" type="MANA"/>
      <casttime value="1"/>
      <cooldown value="5"/>
      <targettype value="ENEMY"/>
      <range value="800"/>
      <effects>
        <impact>
          <damage value="20" scaling="FIRE_MAGIC" type="FIRE" target="TARGET">
            <step key="1" value="24"/>
            <step key="2" value="27"/>
            <step key="12" value="68"/>
            <step key="14" value="71"/>
          </damage>
          <condition type="BURNING"  value="1" scaling="FIRE_MAGIC" target="TARGET">
            <step key="4" value="2"/>
            <step key="12" value="3"/>
          </condition>
        </impact>
      </effects>
    </spell>

    <spell type="SPELL">
      <name value="Glowing Glaze"/>
      <costs value="5" type="MANA"/>
      <casttime value="1"/>
      <cooldown value="8"/>
      <targettype value="ENEMY"/>
      <range value="800"/>
      <effects>
        <impact>
          <damage value="5" scaling="FIRE_MAGIC" type="FIRE" target="TARGET">
            <step key="1" value="5"/>
            <step key="2" value="8"/>
            <step key="3" value="11"/>
            <step key="4" value="14"/>
            <step key="5" value="17"/>
            <step key="6" value="20"/>
            <step key="7" value="23"/>
            <step key="8" value="29"/>
            <step key="9" value="32"/>
            <step key="10" value="35"/>
            <step key="11" value="38"/>
            <step key="12" value="41"/>
            <step key="13" value="44"/>
            <step key="14" value="47"/>
          </damage>
          <when value="TARGET">
            <whencondition>
              <condi type="FIRE"/>
            </whencondition>
            <then>
              <givemana value="1" scaling="ENERGY_STORAGE" target="SELF">
                <step key="2" value="5"/>
                <step key="4" value="6"/>
                <step key="6" value="7"/>
                <step key="8" value="8"/>
                <step key="10" value="9"/>
                <step key="12" value="10"/>
                <step key="14" value="11"/>
              </givemana>
            </then>
          </when>
        </impact>
      </effects>
    </spell>

    <spell type="Spell">
      <name value="Aura of Resoration"/>
      <costs value="5" type="MANA"/>
      <casttime value="0.25"/>
      <cooldown value="30"/>
      <targettype value="SELF"/>
      <range value="0"/>
      <effects>
        <impact>
          <buff value="30" scaling="NONE" usage="INF" type="ENCHANTMENT" trigger="AFTERCAST">
            <heal value="200" target="SELF" scaling="ENERGY_STORAGE">
              <step key="1" value="213"/>
              <step key="2" value="227"/>
              <step key="3" value="240"/>
              <step key="4" value="253"/>
              <step key="5" value="267"/>
              <step key="6" value="280"/>
              <step key="7" value="293"/>
              <step key="8" value="307"/>
              <step key="9" value="320"/>
              <step key="10" value="333"/>
              <step key="11" value="347"/>
              <step key="12" value="360"/>
              <step key="13" value="373"/>
              <step key="14" value="387"/>
            </heal>
            <givemana value="0" scaling="ENERGY_STORAGE" target="SELF">
              <step key="8" value="1"/>
            </givemana>
          </buff>
        </impact>
      </effects>
    </spell>
  
  <spell type="UNIQUE_BUFF">
    <name value="Glyph of Lesser Energy"/>
    <costs value="5" type="MANA"/>
    <casttime value="1"/>
    <cooldown value="30"/>
    <targettype value="SELF"/>
    <range value="0"/>
  <effects>
    <impact>
      <buff value="15" scaling="NONE" usage="2" type="GLYPHE" trigger="BEFORECAST">
          <reducemanacost value="10" scaling="ENERGY_STORAGE">
               <step key="1" value="11"/>
                <step key="3" value="12"/>
                <step key="5" value="13"/>
                <step key="7" value="14"/>
                <step key="9" value="15"/>
                <step key="11" value="16"/>
                <step key="13" value="17"/>
          </reducemanacost>
      </buff>
    </impact>
  </effects>
  </spell>
  
  <spell type="SPELL">
    <name value="Fire Attunement"/>
    <costs value="10" type="MANA"/>
    <casttime value="1"/>
    <cooldown value="30"/>
    <targettype value="SELF"/>
    <range value="0"/>
  <effects>
    <impact>
      <buff value="36" scaling="FIRE_MAGIC" type="ENCHANTMENT" usage="INF" trigger="AFTERCAST">
        <givemana value="1" scaling="NONE"  target="SELF"/>
        <givemanavalue value="30" scaling="NONE" target="SELF" type="MANA"/>
      </buff>
    </impact>
  </effects>
  </spell>
  </profession>
  
  <profession value="DERWISH">
		<spell type="SPELL">
			<name value="Mystic Regeneration"/>
			<costs value="10" type="MANA"/>
			<casttime value="0.25"/>
			<cooldown value="12"/>
			<targettype value="SELF"/>
      <range value="0"/>
      <effects>
        <impact>
			    <buff value="5" type="ENCHANTMENT" scaling="EARTH_PRAYERS" usage="INF" trigger="NONE">
				    <step key="1" value="6"/>
				    <step key="2" value="7"/>
				    <step key="3" value="8"/>
				    <foreach type="ENCHANTMENT">
              <regeneration value="1" scaling="EARTH_PRAYERS" type="HEALTH" target="SELF">
						    <step key="3" value="2"/>
						    <step key="8" value="3"/>
					    </regeneration>
				    </foreach>
			    </buff>
        </impact>
      </effects>
		</spell>
  
  <spell type="SPELL">
    <name value="Mirage Cloak"/>
    <costs value="10" type="MANA"/>
    <casttime value="0"/>
    <cooldown value="10"/>
    <targettype value="SELF"/>
    <range value="0"/>
    <effects>
      <impact>
        <buff value="1" scaling="EARTH_PRAYERS" type="ENCHANTMENT" usage="INF" trigger="DAMAGE">
          <block value="40" scaling="EARTH_PRAYERS" type="ATTACKS" usage="INF">
              <step key="1" value="43"/>
              <step key="2" value="45"/>
              <step key="3" value="48"/>
              <step key="4" value="51"/>
              <step key="5" value="53"/>
              <step key="6" value="56"/>
              <step key="7" value="59"/>
              <step key="8" value="61"/>
              <step key="9" value="64"/>
              <step key="10" value="67"/>
              <step key="11" value="69"/>
              <step key="12" value="72"/>
              <step key="13" value="75"/>
              <step key="14" value="77"/>
          </block>
        </buff>
      </impact>
    </effects>
  </spell>
</profession>

  

</skills>
