=== dangari/Herobattle/Herobattle/Content/Definitions/skill.dtd
<!ELEMENT skills (profession)*>

<!ELEMENT profession (spell)*>
<!ATTLIST  profession
	value CDATA #REQUIRED
>

<!ELEMENT spell (name, costs, casttime, cooldown, targettype, range, weapon?, effects)>
<!ATTLIST spell
  type CDATA #REQUIRED
  >
<!-- spell nodes  -->
<!ELEMENT name EMPTY>
<!ATTLIST name
  value CDATA #REQUIRED
  >
<!ELEMENT costs EMPTY>
<!ATTLIST costs
  value CDATA #REQUIRED
  type (MANA|ADRENALINE|NONE) #REQUIRED
  >
<!ELEMENT casttime EMPTY>
<!ATTLIST casttime
  value CDATA #REQUIRED
  >
<!ELEMENT cooldown EMPTY>
<!ATTLIST cooldown
  value CDATA #REQUIRED
  >
<!ELEMENT targettype EMPTY>
<!ATTLIST targettype
  value (SELF|SELFFRIEND|FRIEND|ENEMY) #REQUIRED
  >
<!ELEMENT range EMPTY>
<!ATTLIST range
  value CDATA #REQUIRED
  >

<!ELEMENT weapon EMPTY>
<!ATTLIST weapon 
  value CDATA #REQUIRED
  >


<!ELEMENT effects (impact)>
<!-- impact nodes  -->
<!ELEMENT impact (heal|damage|buff|condition|foreach|when|remove|givemana|giveadrenaline)*>
<!ELEMENT heal (step?)*>
<!ATTLIST heal 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  trigger (HEAL|DAMAGE|CAST|CASTMANA) #IMPLIED
  >
<!ELEMENT damage (step?)*>
<!ATTLIST damage 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  trigger (HEAL|DAMAGE|CAST) #IMPLIED
  >
<!ELEMENT buff (step?|heal|damage|buff|regeneration|foreach|when|block|knockdown|skillcooldown|reducemanacost|givemana|givemanavalue|giveadrenaline|damagereduction|immune|attackspeed|movementspeed)*>
<!ATTLIST buff 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  usage CDATA #REQUIRED
  trigger (HIT|AFTERCAST|BEFORECAST|AFTERATTACK|DAMAGE|HEAL|NONE) #REQUIRED
  >
<!ELEMENT condition (step)*>
<!ATTLIST condition 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  >
<!ELEMENT regeneration (step?)*>
<!ATTLIST regeneration 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  >
<!ELEMENT foreach (heal|damage|buff|condition|regeneration|when|givemana|giveadrenaline)*>
<!ATTLIST foreach
  type CDATA #REQUIRED
  >
<!ELEMENT when (whencondition, then)>
<!ATTLIST when
  value CDATA #REQUIRED
  >
<!ELEMENT whencondition (attack|hp|mana|condi|casting|hex)>

<!ELEMENT remove (step?)*>
<!ATTLIST remove 
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!ELEMENT givemana (step?)*>
<!ATTLIST givemana 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!ELEMENT givemanavalue (step?)*>
<!ATTLIST givemanavalue 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  type (MANA|DAMAGe) #REQUIRED
  >

<!ELEMENT giveadrenaline (step?)*>
<!ATTLIST giveadrenaline
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!ELEMENT reducemanacost (step?)*>
<!ATTLIST reducemanacost 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  >

<!ELEMENT damagereduction (step?)*>
<!ATTLIST damagereduction
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  type CDATA #REQUIRED
  target (TARGET|SELF|OWNER) #REQUIRED
  >
<!ELEMENT immune EMPTY>
<!ATTLIST immune 
  type (KNOCKDOWN|HEX|CONDTIONS|CRITS) #REQUIRED
  >

<!ELEMENT attackspeed (step?)*>
<!ATTLIST attackspeed
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!ELEMENT movementspeed (step?)*>
<!ATTLIST movementspeed 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!ELEMENT knockdown (step?)*>
<!ATTLIST knockdown 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >
<!ELEMENT skillcooldown (step?)*>
<!ATTLIST skillcooldown 
  value CDATA #REQUIRED
  scaling CDATA #REQUIRED
  type (ALL|CURRENTSKILL|INTERRUPT|ATTRIBUTE) #REQUIRED
  target (TARGET|SELF) #REQUIRED
  >

<!-- sub nodes -->
<!ELEMENT then (heal|damage|buff|condition|regeneration|knockdown|skillcooldown|givemana|giveadrenaline|remove)*>

<!ELEMENT attack EMPTY>
<!ATTLIST attack
  type CDATA #REQUIRED
  >
<!ELEMENT hp EMPTY>
<!ATTLIST hp
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  >

<!ELEMENT mana EMPTY>
<!ATTLIST mana
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  >

<!ELEMENT condi EMPTY>
<!ATTLIST condi
  type CDATA #REQUIRED
  >
<!ELEMENT casting EMPTY>

<!ELEMENT hex EMPTY>

<!ELEMENT step EMPTY>
<!ATTLIST step
  key CDATA #REQUIRED
  value CDATA #REQUIRED
  >



<!ELEMENT block (step?)*>
<!ATTLIST block
  value CDATA #REQUIRED
  type CDATA #REQUIRED
  scaling CDATA #REQUIRED
  usage CDATA #REQUIRED
  >

=== dangari/Herobattle/Herobattle/Content/Definitions/Warrior.xml
<!DOCTYPE skills SYSTEM "skill.dtd">
<skills>
	<profession value="PARAGON">
		<spell type="RANGEATTACK">
			<name value="Barbed Spear"/>
			<costs value="2" type="ADRENALINE"/>
			<casttime value="0"/>
			<cooldown value="0"/>
			<targettype value="ENEMY"/>
			<range value="800"/>
			<weapon value="SPEAR"/>
			<effects>
				<impact>
					<condition value="5" scaling="SPEAR_MASTERY" target="TARGET" type="BLEEDING">
						<step key="1" value="6"/>
						<step key="2" value="7"/>
						<step key="3" value="8"/>
						<step key="4" value="9"/>
						<step key="5" value="10"/>
						<step key="6" value="11"/>
						<step key="7" value="12"/>
						<step key="8" value="13"/>
						<step key="9" value="14"/>
						<step key="10" value="15"/>
						<step key="11" value="16"/>
						<step key="12" value="17"/>
						<step key="13" value="18"/>
						<step key="14" value="19"/>
					</condition>
				</impact>
			</effects>
		</spell>
		<spell type="RANGEATTACK">
			<name value="Maiming Spear"/>
			<costs value="5" type="MANA"/>
			<casttime value="0"/>
			<cooldown value="5"/>
			<targettype value="ENEMY"/>
			<range value="800"/>
			<weapon value="SPEAR"/>
			<effects>
				<impact>
					<when value="TARGET">
						<whencondition>
							<condi type="BLEEDING"/>
						</whencondition>
						<then>
							<condition value="5" scaling="SPEAR_MASTERY" target="TARGET" type="CRIPPLED">
								<step key="1" value="6"/>
								<step key="2" value="7"/>
								<step key="3" value="8"/>
								<step key="4" value="9"/>
								<step key="5" value="10"/>
								<step key="6" value="11"/>
								<step key="7" value="12"/>
								<step key="8" value="13"/>
								<step key="9" value="14"/>
								<step key="10" value="15"/>
								<step key="11" value="16"/>
								<step key="12" value="17"/>
								<step key="13" value="18"/>
								<step key="14" value="19"/>
							</condition>
						</then>
					</when>
				</impact>
			</effects>
		</spell>
		<spell type="RANGEATTACK">
			<name value="Blazing Spear"/>
			<costs value="6" type="ADRENALINE"/>
			<casttime value="0"/>
			<cooldown value="0"/>
			<targettype value="ENEMY"/>
			<range value="800"/>
			<weapon value="SPEAR"/>
			<effects>
				<impact>
					<damage value="5" scaling="SPEAR_MASTERY" target="TARGET" type="ATTACK">
						<step key="1" value="6"/>
						<step key="2" value="8"/>
						<step key="3" value="9"/>
						<step key="4" value="10"/>
						<step key="5" value="12"/>
						<step key="6" value="13"/>
						<step key="7" value="14"/>
						<step key="8" value="16"/>
						<step key="9" value="17"/>
						<step key="10" value="18"/>
						<step key="11" value="20"/>
						<step key="12" value="21"/>
						<step key="13" value="22"/>
						<step key="14" value="24"/>
					</damage>
					<condition value="1" scaling="SPEAR_MASTERY" target="TARGET" type="BURNING">
						<step key="4" value="2"/>
						<step key="12" value="3"/>
					</condition>
				</impact>
			</effects>
		</spell>
		<spell type="RANGEATTACK">
			<name value="Stunning Strike"/>
			<costs value="6" type="ADRENALINE"/>
			<casttime value="0"/>
			<cooldown value="0"/>
			<targettype value="ENEMY"/>
			<range value="800"/>
			<weapon value="SPEAR"/>
			<effects>
				<impact>
					<damage value="5" scaling="SPEAR_MASTERY" target="TARGET" type="ATTACK">
						<step key="1" value="7"/>
						<step key="2" value="8"/>
						<step key="3" value="10"/>
						<step key="4" value="12"/>
						<step key="5" value="13"/>
						<step key="6" value="15"/>
						<step key="7" value="17"/>
						<step key="8" value="18"/>
						<step key="9" value="20"/>
						<step key="10" value="22"/>
						<step key="11" value="23"/>
						<step key="12" value="25"/>
						<step key="13" value="27"/>
						<step key="14" value="28"/>
					</damage>
					<when value="TARGET">
						<whencondition>
							<condi type="NONE"/>
						</whencondition>
						<then>
							<condition value="4" scaling="SPEAR_MASTERY" target="TARGET" type="DAZED">
								<step key="2" value="5"/>
								<step key="4" value="6"/>
								<step key="7" value="7"/>
								<step key="9" value="8"/>
								<step key="12" value="9"/>
								<step key="14" value="10"/>
							</condition>
						</then>
					</when>
				</impact>
			</effects>
		</spell>
	</profession>
	<profession value="WARRIOR">
		<spell type="UNIQUE_BUFF">
			<name value="Flail"/>
			<costs value="4" type="ADRENALINE"/>
			<casttime value="0"/>
			<cooldown value="0"/>
			<targettype value="SELF"/>
			<range value="0"/>
			<effects>
				<impact>
					<buff value="1" scaling="STRENGTH" usage="INF" trigger="NONE" type="STANCE">
						<step key="1" value="2"/>
						<step key="2" value="3"/>
						<step key="3" value="4"/>
						<step key="4" value="5"/>
						<step key="5" value="6"/>
						<step key="6" value="7"/>
						<step key="7" value="8"/>
						<step key="8" value="8"/>
						<step key="9" value="9"/>
						<step key="10" value="10"/>
						<step key="11" value="11"/>
						<step key="12" value="12"/>
						<step key="13" value="13"/>
						<step key="14" value="14"/>
						<attackspeed value="33" scaling="NONE" target="SELF"/>
						<movementspeed value="-33" scaling="NONE" target="SELF"/>
					</buff>
				</impact>
			</effects>
		</spell>
		<spell type="UNIQUE_BUFF">
			<name value="Enraging Charge"/>
			<costs value="5" type="MANA"/>
			<casttime value="0"/>
			<cooldown value="20"/>
			<targettype value="SELF"/>
			<range value="0"/>
			<effects>
				<impact>
					<buff value="1" scaling="STRENGTH" usage="INF" trigger="NONE" type="STANCE">
						<step key="1" value="6"/>
						<step key="3" value="7"/>
						<step key="4" value="8"/>
						<step key="6" value="9"/>
						<step key="7" value="10"/>
						<step key="9" value="11"/>
						<step key="10" value="12"/>
						<step key="12" value="13"/>
						<step key="13" value="14"/>
						<movementspeed value="25" scaling="NONE" target="SELF"/>
					</buff>
          <buff value="1" scaling="STRENGTH" usage="1" trigger="HIT" type="STANCE">
            <step key="1" value="6"/>
            <step key="3" value="7"/>
            <step key="4" value="8"/>
            <step key="6" value="9"/>
            <step key="7" value="10"/>
            <step key="9" value="11"/>
            <step key="10" value="12"/>
            <step key="12" value="13"/>
            <step key="13" value="14"/>
              <giveadrenaline value="0" scaling="STRENGTH" target="SELF">
                <step key="3" value="1"/>
                <step key="8" value="2"/>
                <step key="13" value="3"/>
              </giveadrenaline>
          </buff>
				</impact>
			</effects>
		</spell>
		<spell type="SKILL">
			<name value="Lion's Comfort"/>
			<costs value="4" type="ADRENALINE"/>
			<casttime value="1"/>
			<cooldown value="1"/>
			<targettype value="SELF"/>
			<range value="0"/>
			<effects>
				<impact>
					<heal value="50" scaling="STRENGTH" target="SELF">
						<step key="1" value="54"/>
						<step key="2" value="58"/>
						<step key="3" value="62"/>
						<step key="4" value="66"/>
						<step key="5" value="70"/>
						<step key="6" value="74"/>
						<step key="7" value="78"/>
						<step key="8" value="82"/>
						<step key="9" value="86"/>
						<step key="10" value="90"/>
						<step key="11" value="94"/>
						<step key="12" value="98"/>
						<step key="13" value="102"/>
						<step key="14" value="106"/>
					</heal>
					<giveadrenaline value="0" scaling="STRENGTH" target="SELF">
						<step key="3" value="1"/>
						<step key="8" value="2"/>
						<step key="13" value="3"/>
					</giveadrenaline>
				</impact>
			</effects>
		</spell>
		<spell type="UNIQUE_BUFF">
			<name value="Shield Bash"/>
			<costs value="5" type="MANA"/>
			<casttime value="0"/>
			<cooldown value="20"/>
			<targettype value="SELF"/>
			<range value="0"/>
			<weapon value="SHIELD"/>
			<effects>
				<impact>
					<buff value="5" type="STANCE" scaling="STRENGHT" usage="INF" trigger="DAMAGE">
						<step key="2" value="6"/>
						<step key="4" value="7"/>
						<step key="7" value="8"/>
						<step key="9" value="9"/>
						<step key="12" value="10"/>
						<step key="14" value="11"/>
						<block type="ATTACK" value="100" scaling="NONE" usage="1"/>
						<when value="TARGET">
							<whencondition>
								<attack type="MELEEATTACK"/>
							</whencondition>
							<then>
								<knockdown value="2" scaling="NONE" target="TARGET"/>
								<skillcooldown value="15" type="CURRENTSKILL" scaling="NONE" target="TARGET"/>
							</then>
						</when>
					</buff>
				</impact>
			</effects>
		</spell>
	</profession>
</skills>
